add back terragrunt commands to test with assumed role

diff --git a/.github/workflows/aws-terragrunt-pr-plan.yaml b/.github/workflows/aws-terragrunt-pr-plan.yaml
--- a/.github/workflows/aws-terragrunt-pr-plan.yaml
+++ b/.github/workflows/aws-terragrunt-pr-plan.yaml
@@ -43,34 +43,34 @@ jobs:
       - name: Test assumed role
         run: aws sts get-caller-identity
 
-    #   - name: Terragrunt hcl check
-    #     run: terragrunt hclfmt --terragrunt-check
+      - name: Terragrunt hcl check
+        run: terragrunt hclfmt --terragrunt-check
 
-    #   - name: Terraform fmt check
-    #     run: terraform fmt -check -recursive
+      - name: Terraform fmt check
+        run: terraform fmt -check -recursive
 
-    #   - name: Terragrunt validate check
-    #     run: terragrunt validate-all
-    #     env:
-    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-    #       AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
+      - name: Terragrunt validate check
+        run: terragrunt validate-all
+        # env:
+        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        #   AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
 
-    #   - name: Terragrunt Plan
-    #     id: terragrunt_plan
-    #     run: |
-    #       terragrunt plan --terragrunt-non-interactive -out plan.out
-    #       terragrunt show --terragrunt-non-interactive -no-color -json plan.out > plan.json
-    #     continue-on-error: true # Continue on error to ensure the plan is added as a comment on the PR.
-    #     env:
-    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-    #       AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
+      - name: Terragrunt Plan
+        id: terragrunt_plan
+        run: |
+          terragrunt plan --terragrunt-non-interactive -out plan.out
+          terragrunt show --terragrunt-non-interactive -no-color -json plan.out > plan.json
+        continue-on-error: true # Continue on error to ensure the plan is added as a comment on the PR.
+        # env:
+        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        #   AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
 
-    # #   - uses: liatrio/terraform-change-pr-commenter@v1.3.2
-    # #     with:
-    # #       json-file: ${{ inputs.WORKING_DIR }}/plan.json
+    #   - uses: liatrio/terraform-change-pr-commenter@v1.3.2
+    #     with:
+    #       json-file: ${{ inputs.WORKING_DIR }}/plan.json
 
-    #   - name: Status
-    #     if: contains(steps.*.outcome, 'failure')
-    #     run: exit 1
+      - name: Status
+        if: contains(steps.*.outcome, 'failure')
+        run: exit 1
